### PR TITLE
[TASK] use namespaced classes, code cleanup cg

### PR DESCRIPTION
**Pull request by kaystrobach**

### CODE REVIEW

**Comment by Outdoorsman** [comment]
@kaystrobach, does this pull request make sf_tv2fluidge near to TYPO3 7.6 compatible?

**Comment by Outdoorsman** [comment]
Sure hope this gets merged... just noticed that the last PR similar to this (#104) has been sitting for near 1.5 years.

**Comment by kaystrobach** [comment]
I just tested against a 6.2 LTS installation, but removed most of the legacy classes and code usage, so it should work with 7.6 - but needs some testing

**Comment by kaystrobach** [comment]
@Outdoorsman please feel free to test, feedback is welcome. As always this is OpenSource, so any contribution is helpfull ...

TYPO3 ~ Inspiring people to share 😄

**Comment by kaystrobach** [comment]
and I already had tight contact to @derhansen for review

**Comment by Outdoorsman** [comment]
Yeah glad to hear that! Thanks for the feedback @kaystrobach. Very kind of you to submit this.

I'm a little in trouble though because I migrated several templavoila sites to templavoilaplus and don't know if it's a lost cause or if this extension could be made to work for that one too? Just submitted an issue to at least document the thought for others too (#112).

_PS: I see that one person has [already merged your PR](https://github.com/4viewture/sf_tv2fluidge)._

**Comment by kaystrobach** [comment]
It might work, as it is mainly a namespace thingy, but lets start with refactoring and code cleanup and then add more functionality.

The Link shows the branch to this PR and is in the org of my company, so it is basily the git repo I'm working on 😄

**Comment by derhansen** [comment]
Merged into development branch

**Pull request closed without merging**
